export default {
  FETCH_POPULAR_SHOWS_START: 'FETCH_POPULAR_SHOWS_START',
  FETCH_POPULAR_SHOWS_FAILED: 'FETCH_POPULAR_SHOWS_FAIL',
  FETCH_POPULAR_SHOWS_SUCCESS: 'FETCH_POPULAR_SHOWS_SUCCESS',
  FETCH_MORE_TV_START: 'FETCH_MORE_TV_START',
  FETCH_MORE_TV_SUCCESS: 'FETCH_MORE_TV_SUCCESS',
  FETCH_MORE_TV_FAILED: 'FETCH_MORE_TV_FAILED',
};
